### ISSUE TITLE
Pretrained model weights

### ISSUE THREAD

**Issue by ariel415el** [UT-Austin-Data-Science-Group/CSW#1]
Hi, 
Thank you for uploading the code to your work,
Are you intending to upload the weights for any of your trained models.
I'm particularly interested in the Celeb-A models

**Comment by khainb** [comment]
Thank you for asking. I'm sorry for not getting back to you sooner. I lost access to the server for a few months and I have just had access again recently. I have uploaded the pre-trained models for SW, CSW-b, CSW-s, and CSW-d with all settings of the number of projections on CelebA  dataset at the link below. 

https://drive.google.com/file/d/1RILLG5ob8LQ4lMODYBAcd5R8ExcurBfm/view?usp=share_link
